modLoader = "javafml"
loaderVersion = "[40,)"
license = "GNU 3.0"

[[mods]]
modId = "spectacular"
version = "${file.jarVersion}"
displayName = "Spectacular Mod"
description = "Un mod simple d'exemple pour Minecraft"

[[dependencies.spectacular]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.spectacular]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"
